### ISSUE TITLE
Add content to each pages

### ISSUE THREAD

**Issue by VioAlbert** [VioAlbert/jollybee-web#2]
## Tasks

- [ ] Add content for About Page
- [ ] Add content for Learn Page
- [ ] Add content for Register Page
- [ ] Add styles if needed
